#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
  configure)
    sed -i 's#:latest#:develop#g' /etc/systemd/system/flecs-*
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    ;;
esac

exit 0
