FROM debian:buster-slim

ENV DEBIAN_FRONTEND=noninteractive

COPY build-utils/docker/scripts/debian/install-packages.sh /tmp/

RUN /tmp/install-packages.sh automake build-essential cmake gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf \
    g++-aarch64-linux-gnu g++-arm-linux-gnueabihf git libtool npm sharutils
