[workspace]
resolver = "2"
members = ["flecs-core", "flecsd", "flecsd_axum_server", "flecstract", "flecs-console-api/flecs_console_client", "flecs_app_manifest", "examples"]

[workspace.package]
rust-version = "1.86.0"
edition = "2024"
license = "Apache-2.0"
authors = ["FLECS Technologies GmbH"]
