name: build our image

on:
  push:
    branches: main
    paths:
      - 'docker/flecs-build/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build 'flecs-build' image
        run: |
          docker buildx build \
            --tag flecs/flecs-build:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
