#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case $1 in
  abort-upgrade)
    ;;
  failed-upgrade)
    ;;
  upgrade)
    if dpkg --compare-versions "$2" lt "5.0.0-red-deer"; then
      docker run --rm -v flecsd:/flecs alpine:latest mv /flecs/providers/providers.json /flecs/providers/providers.json.pre-downgrade
    fi
    ;;
  purge)
    rm -rf /var/lib/flecs
    ;;
esac

exit 0
