#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

case $1 in
  abort-upgrade)
    ;;
  configure|abort-remove)
    flecsd.sh migrate || exit 1
    systemctl preset flecs
    systemctl is-enabled flecs >/dev/null && systemctl start flecs
    ;;
esac

exit 0
