#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case $1 in
  abort-upgrade)
    ;;
  failed-upgrade)
    ;;
  upgrade)
    ;;
  purge)
    rm -rf /var/lib/flecs
    ;;
esac

exit 0
