#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

case $1 in
  failed-upgrade)
    ;;
  upgrade)
    # TODO implement graceful detach in flecsd
    echo "Detaching flecs.service"
    systemctl kill --signal=KILL flecs
    ;;
  remove)
    echo "Disabling flecs.service"
    systemctl disable --now flecs
    ;;
esac

exit 0
