/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivationData {
    #[serde(rename = "sessionId")]
    pub session_id: Box<models::SessionId>,
    #[serde(rename = "licenseKey")]
    pub license_key: String,
}

impl ActivationData {
    pub fn new(session_id: models::SessionId, license_key: String) -> ActivationData {
        ActivationData {
            session_id: Box::new(session_id),
            license_key,
        }
    }
}
