/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv2AuthValidatePostRequest {
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<Box<models::Jwt1>>,
}

impl Apiv2AuthValidatePostRequest {
    pub fn new() -> Apiv2AuthValidatePostRequest {
        Apiv2AuthValidatePostRequest { jwt: None }
    }
}
