/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureFlags1 {
    #[serde(rename = "ff", skip_serializing_if = "Option::is_none")]
    pub ff: Option<Box<models::Ff>>,
}

impl FeatureFlags1 {
    pub fn new() -> FeatureFlags1 {
        FeatureFlags1 { ff: None }
    }
}
