/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ff {
    #[serde(rename = "isVendor", skip_serializing_if = "Option::is_none")]
    pub is_vendor: Option<bool>,
    #[serde(rename = "isWhitelabeled", skip_serializing_if = "Option::is_none")]
    pub is_whitelabeled: Option<bool>,
}

impl Ff {
    pub fn new() -> Ff {
        Ff {
            is_vendor: None,
            is_whitelabeled: None,
        }
    }
}
