/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2Tokens200ResponseData {
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<models::PostApiV2Tokens200ResponseDataToken>>,
}

impl PostApiV2Tokens200ResponseData {
    pub fn new() -> PostApiV2Tokens200ResponseData {
        PostApiV2Tokens200ResponseData { token: None }
    }
}
