/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2DeviceLicenseActivate200Response {
    #[serde(rename = "data")]
    pub data: Box<models::ActivationData>,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    #[serde(rename = "statusText", skip_serializing_if = "Option::is_none")]
    pub status_text: Option<String>,
}

impl PostApiV2DeviceLicenseActivate200Response {
    pub fn new(data: models::ActivationData) -> PostApiV2DeviceLicenseActivate200Response {
        PostApiV2DeviceLicenseActivate200Response {
            data: Box::new(data),
            status_code: None,
            status_text: None,
        }
    }
}
