#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
  remove)
    sed -i 's#:develop#:latest#g' /etc/systemd/system/flecs-*
    sed -i 's#:develop#:latest#g' /usr/bin/flecs-updater
    ;;
  *)
    ;;
esac

exit 0
