#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case $1 in
  abort-upgrade)
    ;;
  configure|abort-remove)
    systemctl preset ##PACKAGE##
    systemctl is-enabled ##PACKAGE## >/dev/null && systemctl start ##PACKAGE## || true
    ;;
esac

exit 0
