server {
    resolver 127.0.0.11;
    listen       80;
    server_name  floxy;

    include /floxy/*.conf;

    #location / {
    #    return 301 $scheme://$http_host/editor$request_uri;
    #}

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
