version: "3.7"

services:
  flecsd:
    image: flecs/flecs-slim:4.0.0-snowhare-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - flecsd:/var/lib/flecs
    restart: always
    network_mode: host
    command: 172.21.0.1

  webapp:
    image: flecs/webapp:4.0.0-snowhare-dev
    ports:
      - 8081:80
    depends_on:
      - flecsd
    restart: always
    extra_hosts:
      - flecs-flecsd:172.21.0.1
    networks:
      flecs:
        ipv4_address: 172.21.255.254

volumes:
  flecsd:

networks:
  flecs:
    name: flecs
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
