#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
  configure)
    docker network create flecs-internal >/dev/null 2>&1
    systemctl enable --now flecs-backend
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    ;;
esac

exit 0
