name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --examples -- -D warnings

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: build
        shell: bash
        run: |
          mkdir -p build && cd build 
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: make examples
        shell: bash
        run: |
          cd build
          cmake --build . --target examples

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: zenoh-c-${{ matrix.os }}
          # Directory containing files to upload
          path: |
            target/release
            !target/release/build
            !target/release/deps
            !target/release/.*
            !target/release/*.d
