error_log /var/log/nginx/error.log;
pid       /var/run/nginx.pid;

events {
  worker_connections  1024;
}

http {
    access_log          /var/log/nginx/access.log;
    sendfile            on;
    keepalive_timeout   65;
    server {
        listen       50005;
        server_name  floxy;

        location = /api/v2/imports {
            client_max_body_size 8G;
            proxy_request_buffering off;
            proxy_pass http://flecs-flecsd:8951/v2/imports;
        }

        include /var/lib/flecs/floxy/*.conf;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        location / {
            proxy_pass http://flecs-flecsd:8951/;
        }
    }
}
