error_log /tmp/error.log;
pid       /tmp/nginx.pid;

events {
  worker_connections  1024;
}

http {
    server {
        access_log /tmp/nginx_host.access.log;
        client_body_temp_path /tmp/client_body;
        fastcgi_temp_path /tmp/fastcgi_temp;
        proxy_temp_path /tmp/proxy_temp;
        scgi_temp_path /tmp/scgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        listen       50005;
        server_name  floxy;

        location = /api/v2/imports {
            client_max_body_size 8G;
            proxy_request_buffering off;
            proxy_pass http://flecs-flecsd:8951/v2/imports;
        }

        include /var/lib/flecs/floxy/instances/*.conf;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        location / {
            proxy_pass http://flecs-flecsd:8951/;
        }
    }
}
