#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case $1 in
  abort-upgrade)
    ;;
  configure|abort-remove)
    /opt/flecsd/bin/flecsd.sh migrate || exit 1
    systemctl preset ##PACKAGE##
    systemctl is-enabled ##PACKAGE## >/dev/null && systemctl start ##PACKAGE##
    ;;
esac

exit 0
