on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  check:
    uses: FLECS-Technologies/actions-rs/.github/workflows/check.yml@main
    with:
      flecs_build_ref: develop