name: Develop

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: flecs/flecs-build

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Disable git security"
        run: |
          git config --system --add safe.directory "*"
      - name: "CMake: Configure"
        run: |
          git config --system --add safe.directory "*"
          cmake -G Ninja -B build/${{ matrix.arch }} -DARCH=${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=out/${{ matrix.arch }}
      - name: "CMake: Build"
        run: |
          cmake --build build/${{ matrix.arch }}
      - name: "CMake: Install"
        run: |
          cmake --build build/${{ matrix.arch }} --target install
      - name: "CMake: Package"
        run: |
          cmake --build build/${{ matrix.arch }} --target packages

      - name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: packages_${{ matrix.arch }}
          path: |
            out/${{ matrix.arch }}/*.deb
          retention-days: 3

      - name: Deploy packages
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MP_GITHUB_SERVER }}
          username: ${{ secrets.MP_GITHUB_USER }}
          key: ${{ secrets.MP_GITHUB_SSH_KEY }}
          passphrase: ${{ secrets.MP_GITHUB_SSH_KEY_PW }}
          source: "out/${{ matrix.arch }}/*.deb"
          target: "${{ secrets.MP_GITHUB_DEVELOP_DIR }}/deb/"
          strip_components: 2

      - name: Deploy latest file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MP_GITHUB_SERVER }}
          username: ${{ secrets.MP_GITHUB_USER }}
          key: ${{ secrets.MP_GITHUB_SSH_KEY }}
          passphrase: ${{ secrets.MP_GITHUB_SSH_KEY_PW }}
          source: "out/${{ matrix.arch }}/latest_flecs_${{ matrix.arch }}"
          target: "${{ secrets.MP_GITHUB_DEVELOP_DIR }}/"
          strip_components: 2
