name: Develop

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: flecs/flecs-build

    steps:
      - uses: actions/checkout@v2
      - name: native
        run: |
          make DOCKERLESS=1 -C build/ flecs
      - name: armhf
        run: |
          make DOCKERLESS=1 -C build/ CROSS_COMPILE=arm-linux-gnueabihf flecs
      - name: aarch64
        run: |
          make DOCKERLESS=1 -C build/ CROSS_COMPILE=aarch64-linux-gnu flecs
      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            **/*.deb
            **/*.ipk
          retention-days: 3
      - name: Archive raw artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: |
            ui/backend/out
            daemon/out
            !**/*.deb
            !**/*.ipk
          retention-days: 1

  docker:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Download workflow artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
      - name: native
        run: |
          make DOCKERLESS=1 -C build/ updater/docker
