name: Develop

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    uses: ./.github/workflows/build.yml
    with:
      arch: ${{ matrix.arch }}
      build_type: Debug
      cmake_args: ""
      flecs_build_ref: develop

  deploy-dl:
    needs: build

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    uses: ./.github/workflows/deploy-dl.yml
    with:
      arch: ${{ matrix.arch }}
      deploy_dir: dev
    secrets: inherit

  deploy-cr:
    needs: build

    uses: ./.github/workflows/deploy-cr.yml
    with:
      docker_ref: develop
    secrets: inherit
