name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    uses: ./.github/workflows/build.yml
    with:
      arch: ${{ matrix.arch }}
      build_type: Debug
      flecs_build_ref: develop

  test:
    strategy:
      matrix:
        arch: ["amd64"]

    uses: ./.github/workflows/test.yml
    with:
      flecs_build_ref: develop
