name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: cr.flecs.tech/flecs-build

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Disable git security"
        run: |
          git config --system --add safe.directory "*"
      - name: "CMake: Configure"
        run: |
          cmake -G Ninja -B build/${{ matrix.arch }} -DARCH=${{ matrix.arch }} -DCMAKE_INSTALL_PREFIX=out/${{ matrix.arch }}
      - name: "CMake: Build"
        run: |
          cmake --build build/${{ matrix.arch }}
      - name: "CMake: Install"
        run: |
          cmake --build build/${{ matrix.arch }} --target install

  test:
    runs-on: ubuntu-22.04
    container: cr.flecs.tech/flecs-build

    strategy:
      matrix:
        arch: ["amd64"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Disable git security"
        run: |
          git config --system --add safe.directory "*"
      - name: "CMake: Configure"
        run: |
          cmake -G Ninja -B build/${{ matrix.arch }} -DARCH=${{ matrix.arch }} -DFLECS_BUILD_TESTS=Yes -DCMAKE_INSTALL_PREFIX=out/${{ matrix.arch }}
      - name: "CMake: Build"
        run: |
          cmake --build build/${{ matrix.arch }}
      - name: "CMake: Test"
        run: |
          cmake --build build/${{ matrix.arch }} --target test
