name: C/C++ CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: flecs/flecs-build

    steps:
      - uses: actions/checkout@v2
      - name: native
        run: |
          make DOCKERLESS=1 -C build/ flecs
      - name: armhf
        run: |
          make DOCKERLESS=1 -C build/ CROSS_COMPILE=arm-linux-gnueabihf flecs
      - name: aarch64
        run: |
          make DOCKERLESS=1 -C build/ CROSS_COMPILE=aarch64-linux-gnu flecs
