name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: flecs/flecs-build

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    steps:
      - uses: actions/checkout@v3
      - name: "CMake: Configure"
        run: |
          cmake -G Ninja -B out/${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE=build/cmake/toolchains/${{ matrix.arch }}.cmake
      - name: "CMake: Build"
        run: |
          cmake --build out/${{ matrix.arch }}
      - name: "CMake: Install"
        run: |
          cmake --build out/${{ matrix.arch }} --target install

  test:
    runs-on: ubuntu-22.04
    container: flecs/flecs-build

    strategy:
      matrix:
        arch: ["amd64"]

    steps:
      - uses: actions/checkout@v3
      - name: "CMake: Configure"
        run: |
          cmake -G Ninja -B out/${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE=build/cmake/toolchains/${{ matrix.arch }}.cmake -DFLECS_BUILD_TESTS=Yes
      - name: "CMake: Build"
        run: |
          cmake --build out/${{ matrix.arch }}
      - name: "CMake: Test"
        run: |
          cmake --build out/${{ matrix.arch }} --target test
