on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '17 3 * * *'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: FLECS-Technologies/actions-rs
          ref: main
          sparse-checkout: |
            .cargo/audit.toml
          path: './audit'
      - name: Copy cargo audit config
        run: cp -r ./audit/.cargo .
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
